// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommentAndReply: typeof import('./src/components/CommentAndReply.vue')['default']
    CommentAndReplyList: typeof import('./src/components/CommentAndReplyList.vue')['default']
    CommentAndReplyOneData: typeof import('./src/components/CommentAndReplyOneData.vue')['default']
    CommentAndReplyRawData: typeof import('./src/components/CommentAndReplyRawData.vue')['default']
    CommentAndReplyTree: typeof import('./src/components/CommentAndReplyTree.vue')['default']
    CommentReply: typeof import('./src/components/CommentReply.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
